### ISSUE TITLE
README does not inform the user which repository this project is available from

### ISSUE THREAD

**Issue by jeremygiberson** [americanexpress/nodes#12]
Not familiar with the Java eco system, it was non obvious to me to try jcenter to find the dependency. It should probably be mentioned in the read me and included in the maven  install examples.

Maven
```
<repositories>
    <repository>
            <id>jcenter - amex</id>
            <url>https://dl.bintray.com/americanexpress/maven/</url>
    </repository>
</repositories>
```

**Comment by chemdrew** [comment]
Added this to the readme but not the examples. Since the examples currently install the package from their sibling module I want them to stay synced with that for development and not download and use the release. Makes debugging a lot simpler. Let me know if this clears things up now!
