### ISSUE TITLE
HTTP to HTTPS

### ISSUE THREAD

**Issue by asanajiun** [americanexpress/nodes#31]
Enhancement: consider supporting HttpsURLConnection 
javax.net.ssl.HttpsURLConnection
in order to request secure https API endpoints.

**Comment by chemdrew** [comment]
Hi @asanajiun,
HttpsURLConnection simply extends HttpURLConnection and still provides the the same ssl validation of https endpoints. It just adds some more methods for dealing with the ssl response.

Both http and https endpoints are currently supported in the library and ssl validation is performed for https endpoints.
