### ISSUE TITLE
Testing Input Object . 

### ISSUE THREAD

**Issue by bpillai** [americanexpress/nodes#38]
Currently in the client since we have protected access over the methods in InputObject it becomes impossible to test an argument that has an input object as the value .

**Comment by chemdrew** [comment]
I am good with there being a public getter method on InputObject

**Comment by bpillai** [comment]
PR - https://github.com/americanexpress/nodes/pull/39/

**Comment by chemdrew** [comment]
👍 will be releasing a new version shortly
