### ISSUE TITLE
Could GraphQLRequestEntity make setRequestMethod as public method?

### ISSUE THREAD

**Issue by WaterZhang** [americanexpress/nodes#55]
Our team use this framework to compose query of GraphQL API call. I saw setRequestMethod method in GraphQLRequestEntity is access only package and GraphQLTemplate call it and change request method. For our program, we use Feign+Hystrix as http call. That means we only use Nodes to compose query.
For my understanding, it is not enough to change setRequestMethod as public method. All initial process finish in GraphQLRequestEntity constructor method.
could expose set up requestMethod (query or mutate) in builder?

**Comment by WaterZhang** [comment]
should expose builder method to set up requestMethod (query or mutate)?

**Comment by chemdrew** [comment]
Adding this to the builder sounds like an excellent idea!

**Comment by WaterZhang** [comment]
Could I give pull request or you could make it change and release new version?

**Comment by chemdrew** [comment]
I will absolutely take the change in a pull request! Otherwise I can make the change fairly quickly either tomorrow or Saturday

**Comment by chemdrew** [comment]
Alright, just released v0.4.0 which should allow you to set the request method in the builder or on the GraphQLRequestEntity instance so you can build the correct query without executing the fetch
