### ISSUE TITLE
Sample with java and sample server graphql

### ISSUE THREAD

**Issue by raulvillalbamedina** [americanexpress/nodes#64]
I need use sample with real graphql api

**Comment by chemdrew** [comment]
Hi @raulvillalbamedina,

[Here is a sample in Kotlin](https://github.com/americanexpress/nodes/tree/master/samples/kotlin-sample) that is included in the repository. There is also a sample in Scala as well.

You can also see some more usage information in these two posts:
[GraphQL for the JVM: An Introduction to Nodes](https://americanexpress.io/graphql-for-the-jvm/)
[Client per la Java Virtual Machine](https://www.html.it/pag/365422/client-per-la-java-virtual-machine/)
