### ISSUE TITLE
0.5.0 release?

### ISSUE THREAD

**Issue by rbraeunlich** [americanexpress/nodes#81]
Hey everyone,
sorry, but I couldn't find another way of contacting you than opening an issue.
Is there any plan for releasing a next version soon? Especially, I'm looking at the changes from PR #75 which I see as basically mandatory for any HTTP connection.
Cheers,
Ronny

**Comment by chemdrew** [comment]
Hey Ronny,
Apologies for the delay in that release.
Available now [here on bintray](https://bintray.com/americanexpress/maven/io.aexp.nodes.graphql/0.5.0)
