### ISSUE TITLE
How to response pack as class

### ISSUE THREAD

**Issue by ghost** [americanexpress/nodes#89]
mutation {
createUser(
    userData: {
        firstName: "Bullhorn", lastName: "Pegas"
        
    }) {
user{

firstName
lastName
}
}
}

- How to write this client in java? I am facing I couldn't pack the response user object. My code is below given

InputObject inputObject = new InputObject.Builder<>().put("firstName", "myname").put("lastName", "Sujith")
				.build();
		GraphQLRequestEntity build = GraphQLRequestEntity.Builder().url("http://192.168.0.182:8000/graphql/")
				.requestMethod(GraphQLMethod.MUTATE)
				.arguments(new Arguments("createUser", new Argument<>("userData", inputObject)))
				.request(TestClass.class).build();
		GraphQLTemplate graphQLTemplate = new GraphQLTemplate();
		System.err.println("Sending request " + build.getRequest());
		GraphQLResponseEntity<TestResponse> execute = graphQLTemplate.mutate(build, TestResponse.class);

import io.aexp.nodes.graphql.annotations.GraphQLArgument;
import io.aexp.nodes.graphql.annotations.GraphQLProperty;
@getter
@setter
@GraphQLProperty(arguments = {
		@GraphQLArgument(name = "firstName"),
		@GraphQLArgument(name = "lastName")
},name = "createUser")
public class TestResponse {
	private String firstName;
	private String lastName;
}

import io.aexp.nodes.graphql.annotations.GraphQLArgument;
import io.aexp.nodes.graphql.annotations.GraphQLProperty;

@GraphQLProperty(name = "createUser", arguments = { @GraphQLArgument(name = "userData") })
@getter
@setter
public class TestClass {
	
	private String firstName;
	private String lastName;

}

**Comment by chemdrew** [comment]
check out [this article](https://americanexpress.io/graphql-for-the-jvm/) for more examples of how to set arguments
