### ISSUE TITLE
Facing issues while querying an API with certain fields but getting an array in response.

### ISSUE THREAD

**Issue by debdiptahalder-4tigo** [americanexpress/nodes#91]
Hi I am trying to query an API which is of the following format.
`query{
  requestallstudentdata{
  id
 name
 hobby
 }
}
`
In response we get something like following:
`{
  "data": {
    "requestallstudentdata": [
      {
        "id": 1,
        "name":"xyz",
        "hobby":"fxdu"
        
      },
      {
      "id": 2,
        "name":"xYz",
        "hobby":"fdu"
      }
    ]
  }
}`

How to handle such requests.Please assist. 
Currently I have the following classes.

I am getting the following response whenever I am trying to send a list.
```
GraphQLException{message='OK', status='200', description='Can not deserialize instance of com.graphql.model.foo.StudentDetails out of START_ARRAY token
 at [Source: N/A; line: -1, column: -1] (through reference chain: io.aexp.nodes.graphql.Wrapper["data"])', errors=null}

```

**Comment by chemdrew** [comment]
ah yeah, querying lists isn't super clear. The same [solution](https://github.com/americanexpress/nodes/issues/26#issuecomment-416696161) in #26 should work here as well.

**Comment by debdiptahalder-4tigo** [comment]
Hi,
Thanks for your reply. I am a bit confused on what to send in the
arguments. I want fetch the list of all the students instead of giving any
specific arguments.
It will be really helpful if you can guide me a bit with this. I do have any arguments to send for querying.

Thanks and Regards,
Debdipta Halder

**Comment by tkosik12** [comment]
@debdiptahalder-4tigo could you tell me what was the solution? If you found it of course.
